/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/sigaa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sigaa Login */
        post: operations["sigaa_login_auth_sigaa_post"];
        /** Sigaa Logout */
        delete: operations["sigaa_logout_auth_sigaa_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sigaa/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sigaa Refresh
         * @description Confere a senha se não houver access_token e agenda o sync do que venceu.
         *
         *     O cache sai só com o refresh_token, então o app chama esta rota ao abrir.
         */
        post: operations["sigaa_refresh_auth_sigaa_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classrooms/{classroom_id}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar notícias de uma turma do usuário
         * @description ID, título e dia das notícias da turma. Cache de 60 minutos, atualizado em segundo plano após vencer; notícias removidas no SIGAA são preservadas.
         */
        get: operations["get_classroom_news_classrooms__classroom_id__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classrooms/{classroom_id}/news/{news_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar conteúdo e anexos de uma notícia da turma
         * @description Texto em Markdown, data e hora e anexos. Conteúdo salvo no primeiro acesso, sem revalidação automática. Cache-Control: no-cache força uma nova consulta.
         */
        get: operations["get_classroom_news_detail_classrooms__classroom_id__news__news_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classrooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar as turmas do usuário autenticado
         * @description Cada turma traz a menção do usuário em grade (null até ser lançada ou sincronizada). A menção é atualizada pelo sync do login e de /auth/sigaa/refresh, e congela depois da consolidação das turmas.
         */
        get: operations["get_classrooms_classrooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classrooms/frequency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar frequência de todas as turmas atuais
         * @description Turmas atuais com identificação e a mesma frequência da rota individual. Falha em uma turma retorna erro, sem omiti-la da lista.
         */
        get: operations["get_current_frequencies_classrooms_frequency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classrooms/{classroom_id}/frequency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar frequência e andamento de uma turma
         * @description Aceita Classroom.id (hash) ou sigaa_id numérico. frequency_status indica nao_registrada, parcialmente_registrada ou registrada nas entradas publicadas. lessons traz as aulas da turma (criadas pelo calendário e horário no sync das turmas, com start_time e end_time) até ontem, as publicadas pelo SIGAA fora delas e as com situação do aluno, mais recentes primeiro; totals soma as marcações aos totais do SIGAA.
         */
        get: operations["get_classroom_frequency_classrooms__classroom_id__frequency_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classrooms/{classroom_id}/frequency/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Marcar presença, falta ou aula cancelada
         * @description Vale enquanto o SIGAA não registra a aula: a chamada publicada substitui a marcação. status null remove a marcação, sem apagar a chamada do SIGAA. Marcar aula que ainda não aconteceu retorna 422.
         */
        patch: operations["mark_lesson_classrooms__classroom_id__frequency_lessons__lesson_id__patch"];
        trace?: never;
    };
    "/classrooms/{classroom_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar docentes e discentes de uma turma do usuário */
        get: operations["get_classroom_members_classrooms__classroom_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classrooms/{classroom_id}/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar a situação dos discentes de uma turma do usuário */
        get: operations["get_classroom_statistics_classrooms__classroom_id__statistics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/classrooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar turmas públicas do SIGAA, sem login
         * @description Consulta diretamente o SIGAA, sem filtrar o nível de ensino. Informe unit ou code. Sem unit, o prefixo de letras do código determina as unidades consultadas pelo índice local; o código completo deve corresponder exatamente. Sem semester, preserva o ano/período do formulário do SIGAA. Com code, retorna 404 se não houver oferta nas unidades e no semestre consultados; isso não confirma que a disciplina inexiste. Se apenas number, contains ou local excluir as turmas encontradas, retorna uma lista vazia (200).
         */
        get: operations["search_classrooms_public_classrooms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/classrooms/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar unidades disponíveis na busca pública de turmas */
        get: operations["list_units_public_classrooms_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/restaurant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar o cardápio público do RU */
        get: operations["get_menu_public_restaurant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar o perfil do usuário autenticado */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/ru-statement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar extrato, saldo e grupo do RU */
        get: operations["get_statement_me_ru_statement_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/ru-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar o token da carteirinha estudantil
         * @description Lê o QR code da carteirinha no SIGAA a cada acesso, sem persistência. Retorna token e valid_until; a validade informa mês/ano e o scraper representa o mês pelo dia 1.
         */
        get: operations["get_token_me_ru_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar as configurações pessoais do usuário */
        get: operations["get_settings_me_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Atualizar as configurações pessoais do usuário */
        patch: operations["update_settings_me_settings_patch"];
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar notícias recentes das turmas na home do SIGAA
         * @description Notícias recentes da home, sem cache.
         */
        get: operations["get_news_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClassroomFrequencyResult */
        ClassroomFrequencyResult: {
            classroom: components["schemas"]["ParticipantClassroom"];
            frequency: components["schemas"]["ClassroomFrequencyView"];
        };
        /** ClassroomFrequencyView */
        ClassroomFrequencyView: {
            progress: components["schemas"]["ClassroomProgress"];
            frequency_status: components["schemas"]["FrequencyStatus"];
            /** Lessons */
            lessons: components["schemas"]["Lesson"][];
            totals: components["schemas"]["FrequencyTotals"] | null;
        };
        /**
         * ClassroomMember
         * @description Participante de uma turma, nos campos da tabela `users` que a tela expõe.
         */
        ClassroomMember: {
            /** Name */
            name: string;
            role: components["schemas"]["ClassroomRole"];
            /** Registration */
            registration?: string | null;
            /** Photo */
            photo?: string | null;
            /** Email */
            email?: string | null;
            /** Course */
            course?: string | null;
            /** Unity */
            unity?: string | null;
            /** Person Id */
            person_id?: number | null;
        };
        /**
         * ClassroomProgress
         * @description O "Andamento das Aulas" da turma virtual: quanto da CH já foi ministrada.
         */
        ClassroomProgress: {
            /** Taught */
            taught: number;
            /** Total */
            total: number;
            /** Percentage */
            percentage: number;
        };
        /**
         * ClassroomRole
         * @enum {string}
         */
        ClassroomRole: "aluno" | "professor" | "monitor";
        /**
         * CurriculumWorkload
         * @description Carga horária do currículo e o que falta integralizar, em horas.
         */
        CurriculumWorkload: {
            /** Total */
            total: number;
            /** Pending Mandatory */
            pending_mandatory: number;
            /** Pending Optional */
            pending_optional: number;
            /** Pending Complementary */
            pending_complementary: number;
        };
        /**
         * DailyMenu
         * @description Refeição que o campus não serve (ou não publicou) no dia vem `None`.
         */
        DailyMenu: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Breakfast */
            breakfast?: components["schemas"]["MenuSection"][] | null;
            /** Lunch */
            lunch?: components["schemas"]["MenuSection"][] | null;
            /** Dinner */
            dinner?: components["schemas"]["MenuSection"][] | null;
        };
        /**
         * FrequencyStatus
         * @description Quanto das entradas publicadas o docente já registrou.
         * @enum {string}
         */
        FrequencyStatus: "nao_registrada" | "parcialmente_registrada" | "registrada";
        /**
         * FrequencyTotals
         * @description Presenças, faltas e frequência do SIGAA somadas às aulas marcadas pelo aluno.
         */
        FrequencyTotals: {
            /** Presences */
            presences: number;
            /** Absences */
            absences: number;
            /** Percentage */
            percentage: number;
            /** Max Absences */
            max_absences: number | null;
            /** Estimated */
            estimated: boolean;
        };
        /**
         * Grade
         * @description Menção da UnB, como o "Resultado" da tela "Ver Notas".
         * @enum {string}
         */
        Grade: "SS" | "MS" | "MM" | "MI" | "II" | "SR";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Lesson
         * @description Uma aula; sem horário quando o SIGAA a publicou numa turma sem horário.
         */
        Lesson: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            status: components["schemas"]["LessonStatus"];
            /**
             * Absences
             * @default 0
             */
            absences: number;
            /**
             * Marked
             * @default false
             */
            marked: boolean;
        };
        /** LessonMarkBody */
        LessonMarkBody: {
            /** Status */
            status: ("presente" | "falta" | "cancelada") | null;
        };
        /**
         * LessonStatus
         * @enum {string}
         */
        LessonStatus: "presente" | "falta" | "nao_registrada" | "cancelada";
        /** MenuSection */
        MenuSection: {
            key?: components["schemas"]["MenuSectionKey"] | null;
            /** Name */
            name: string;
            /** Items */
            items: string[];
        };
        /**
         * MenuSectionKey
         * @enum {string}
         */
        MenuSectionKey: "drink" | "bread" | "extra" | "spread" | "complement" | "complement_vegetarian" | "complement_vegan" | "fruit" | "salad_1" | "salad_2" | "salad_dressing" | "main_dish" | "main_dish_vegetarian" | "main_dish_vegan" | "side_dish" | "accompaniments" | "soup" | "toast" | "dessert";
        /**
         * News
         * @description A home não traz `id`; hora, texto e anexos só vêm de `get_classroom_news`.
         */
        News: {
            /** Id */
            id?: number | null;
            /** Classroom Sigaa Id */
            classroom_sigaa_id?: number | null;
            /** Title */
            title: string;
            /**
             * Published On
             * Format: date
             */
            published_on: string;
            /** Published At */
            published_at?: string | null;
            /** Content */
            content?: string | null;
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["NewsAttachment"][];
        };
        /** NewsAttachment */
        NewsAttachment: {
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /**
         * ParticipantClassroom
         * @description A turma com a menção do usuário, `None` enquanto não lançada ou sincronizada.
         */
        ParticipantClassroom: {
            /** Id */
            id: string;
            /** Sigaa Id */
            sigaa_id?: number | null;
            /** Number */
            number: string;
            /** Semester */
            semester: string;
            /** Schedule */
            schedule?: string | null;
            /** Room */
            room?: string | null;
            /**
             * Current
             * @default false
             */
            current: boolean;
            subject: components["schemas"]["UserSubject"];
            grade?: components["schemas"]["Grade"] | null;
        };
        /**
         * PublicClassroom
         * @description Turma da busca pública.
         *
         *     Não tem `id`: a área pública não expõe o `frontEndIdTurma`, então a
         *     identidade aqui é a chave natural `(subject.code, number, semester)`.
         */
        PublicClassroom: {
            /** Number */
            number: string;
            /** Semester */
            semester: string;
            /** Schedule */
            schedule?: string | null;
            /** Schedule Description */
            schedule_description?: string | null;
            /** Room */
            room?: string | null;
            /** Vacancies */
            vacancies?: number | null;
            /** Occupied */
            occupied?: number | null;
            /**
             * Teachers
             * @default []
             */
            teachers: components["schemas"]["Teacher"][];
            subject: components["schemas"]["Subject"];
        };
        /** RestaurantCredentials */
        RestaurantCredentials: {
            /** Token */
            token: string;
            /**
             * Valid Until
             * Format: date
             */
            valid_until: string;
        };
        /** RestaurantStatement */
        RestaurantStatement: {
            /** Balance */
            balance?: string | null;
            /** Group */
            group?: (1 | 2 | 3 | 4) | null;
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["RestaurantStatementEntry"][];
        };
        /** RestaurantStatementEntry */
        RestaurantStatementEntry: {
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Description */
            description: string;
            /** Amount */
            amount: string;
        };
        /** SigaaLoginRequest */
        SigaaLoginRequest: {
            /** Registration */
            registration: string;
            /** Password */
            password: string;
        };
        /**
         * StatisticsShare
         * @description Uma fatia do gráfico de estatísticas: a porcentagem dos discentes da turma.
         *
         *     O SIGAA arredonda cada fatia em uma casa, então a soma pode fechar em 99.9
         *     ou 100.1. O gráfico não expõe a contagem de alunos, só a porcentagem.
         */
        StatisticsShare: {
            situation: components["schemas"]["StudentSituation"];
            /** Percentage */
            percentage: number;
        };
        /**
         * StudentSituation
         * @description As situações do gráfico "Situação dos Discentes", na ordem da legenda.
         * @enum {string}
         */
        StudentSituation: "aprovado" | "reprovado" | "reprovado_por_faltas" | "reprovado_por_media_e_por_faltas" | "aprovado_por_nota" | "reprovado_por_nota" | "reprovado_por_nota_e_faltas" | "trancado" | "matriculado";
        /**
         * Subject
         * @description Componente curricular, nos campos da tabela `subjects`.
         */
        Subject: {
            /** Code */
            code?: string | null;
            /** Sigaa Id */
            sigaa_id?: number | null;
            /** Name */
            name: string;
            /** Hours */
            hours?: number | null;
            /** Unity */
            unity?: string | null;
        };
        /**
         * Teacher
         * @description Docente de uma turma. `hours` é a carga horária dele naquela turma.
         */
        Teacher: {
            /** Name */
            name: string;
            /** Hours */
            hours?: number | null;
        };
        /**
         * Unit
         * @description Unidade acadêmica ofertante — o filtro obrigatório da busca pública.
         */
        Unit: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * UserLevel
         * @enum {string}
         */
        UserLevel: "Graduação" | "Pós-graduação" | "Mestrado";
        /** UserProfile */
        UserProfile: {
            /** Name */
            name: string;
            /** Registration */
            registration: string;
            /** Photo */
            photo: string | null;
            /** Email */
            email?: string | null;
            /** Bio */
            bio: string | null;
            /** Unity */
            unity: string;
            /** Course */
            course: string;
            /** Integralization */
            integralization: number | null;
            workload: components["schemas"]["CurriculumWorkload"] | null;
            /** Ira */
            ira: number | null;
            /** Mp */
            mp: number | null;
            level: components["schemas"]["UserLevel"];
        };
        /** UserSettings */
        UserSettings: {
            /** Displayname */
            displayName?: string | null;
        };
        /** UserSettingsPatch */
        UserSettingsPatch: {
            /** Displayname */
            displayName?: string | null;
        };
        /**
         * UserSubject
         * @description O componente como o cache guarda, pelo código.
         */
        UserSubject: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Hours */
            hours?: number | null;
            /** Unity */
            unity?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sigaa_login_auth_sigaa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SigaaLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sigaa_logout_auth_sigaa_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sigaa_refresh_auth_sigaa_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_classroom_news_classrooms__classroom_id__news_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path: {
                /** @description Classroom.id ou o classroom_sigaa_id de /news. */
                classroom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"][];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Turma não encontrada entre as turmas do usuário. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cache em atualização. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Notícias ainda não disponíveis no cache. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_classroom_news_detail_classrooms__classroom_id__news__news_id__get: {
        parameters: {
            query?: never;
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path: {
                /** @description Classroom.id ou o classroom_sigaa_id de /news. */
                classroom_id: string;
                /** @description ID da notícia na listagem da turma. */
                news_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Turma fora da lista do usuário ou notícia ausente na turma. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cache em atualização. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conteúdo ainda não disponível no cache. */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_classrooms_classrooms_get: {
        parameters: {
            query?: {
                /** @description Sem filtro: turmas atuais. Use 'all' ou um semestre no formato AAAA.P, como 2026.2. */
                semester?: string | null;
            };
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantClassroom"][];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_current_frequencies_classrooms_frequency_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomFrequencyResult"][];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Turma não encontrada entre as turmas do usuário. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cache em atualização. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_classroom_frequency_classrooms__classroom_id__frequency_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path: {
                /** @description Classroom.id ou Classroom.sigaa_id. */
                classroom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomFrequencyView"];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Turma não encontrada entre as turmas do usuário. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cache em atualização. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mark_lesson_classrooms__classroom_id__frequency_lessons__lesson_id__patch: {
        parameters: {
            query?: never;
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path: {
                /** @description Classroom.id ou Classroom.sigaa_id. */
                classroom_id: string;
                /** @description Lesson.id de uma aula da turma. */
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonMarkBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Turma ou aula não encontrada. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description O SIGAA já registrou a chamada da aula. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_classroom_members_classrooms__classroom_id__members_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path: {
                /** @description Classroom.id ou Classroom.sigaa_id. */
                classroom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassroomMember"][];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Turma não encontrada entre as turmas do usuário. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_classroom_statistics_classrooms__classroom_id__statistics_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path: {
                /** @description Classroom.id ou Classroom.sigaa_id. */
                classroom_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsShare"][];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Turma não encontrada entre as turmas do usuário. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    search_classrooms_public_classrooms_get: {
        parameters: {
            query?: {
                /** @description ID da unidade ou parte do nome, como 'gama'. Obrigatório quando code não for informado. Com code, restringe a busca a esta unidade. Consulte /public/classrooms/units para obter os IDs. */
                unit?: string | null;
                /** @description Opcional, no formato AAAA.P: 2026.2, 2027.1 ou 2026.4. Sem filtro, usa os valores do SIGAA. */
                semester?: string | null;
                /** @description Trecho do nome ou código da disciplina, ou do nome de qualquer docente. Ignora acentos, maiúsculas e espaços extras. Filtra o resultado da unidade/semestre após consultar o SIGAA; vazio não filtra. */
                contains?: string | null;
                /** @description Trecho do local da turma, incluindo unidade e sala, como 'S3', 'FCTE - S3' ou 'auditorio'. Ignora acentos, maiúsculas e espaços extras; vazio não filtra. Com contains, exige correspondência nos dois filtros. */
                local?: string | null;
                /** @description Código completo da disciplina, como MAT0031 ou FGA0132. Ignora maiúsculas e espaços nas extremidades; preserva zeros. Sem unit, consulta todas as unidades mapeadas para o prefixo. Combina com semester, number, contains e local. */
                code?: string | null;
                /** @description Número da turma, de 1 a 99. Aceita com ou sem zero à esquerda: '1' e '01' selecionam a mesma turma. Combina com os demais filtros; use code e semester para identificar a disciplina e o semestre. Sem correspondência, retorna lista vazia. */
                number?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicClassroom"][];
                };
            };
            /** @description Nenhuma turma do código completo nas unidades e no semestre consultados. A disciplina pode não existir ou não ter oferta nessas condições. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Informe unit ou code. Filtro inválido, unidade inexistente ou nome ambíguo. Prefixo ausente do índice pode não existir no SIGAA ou ainda não estar mapeado; informe unit para buscar diretamente. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description SIGAA indisponível ou resposta ilegível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_units_public_classrooms_units_get: {
        parameters: {
            query?: {
                /** @description Filtra pelo nome, ignorando acentos e maiúsculas. */
                contains?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível ou resposta ilegível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_menu_public_restaurant_get: {
        parameters: {
            query?: {
                /** @description Campus do restaurante. */
                campus?: "Darcy" | "Gama" | "Ceilandia" | "Planaltina" | "Fazenda";
                /** @description Dia específico (AAAA-MM-DD). */
                date?: string | null;
                /** @description Início do intervalo (AAAA-MM-DD). */
                start_date?: string | null;
                /** @description Fim do intervalo (AAAA-MM-DD). */
                end_date?: string | null;
                /** @description Retorna apenas a refeição escolhida e a data. Se não publicada no dia, a refeição é null. Sem filtro, retorna todas. */
                meal?: ("breakfast" | "lunch" | "dinner") | null;
            };
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyMenu"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Site do RU indisponível ou cardápio ilegível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description `no-cache` (ou `max-age=0`) busca na origem antes de responder; `max-age=N` aceita cache de até N s; `stale-if-error[=N]` devolve o cache se a origem falhar; `only-if-cached` nunca busca (504 sem cache). */
                "Cache-Control"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_statement_me_ru_statement_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantStatement"];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_token_me_ru_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestaurantCredentials"];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_settings_me_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_settings_me_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettings"];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_news_news_get: {
        parameters: {
            query?: {
                /** @description Resolve os IDs com uma consulta adicional à listagem de notícias por turma. */
                resolve_ids?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["News"][];
                };
            };
            /** @description Credenciais ausentes ou inválidas. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description SIGAA indisponível. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
