/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppRuRouteImport } from './routes/_app/ru'
import { Route as AppTurmasRouteImport } from './routes/_app/turmas'
import { Route as AppTurmasIdRouteImport } from './routes/_app/turmas_.$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppRuRoute = AppRuRouteImport.update({
  id: '/ru',
  path: '/ru',
  getParentRoute: () => AppRoute,
} as any)
const AppTurmasRoute = AppTurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => AppRoute,
} as any)
const AppTurmasIdRoute = AppTurmasIdRouteImport.update({
  id: '/turmas_/$id',
  path: '/turmas/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/perfil': typeof AppPerfilRoute
  '/ru': typeof AppRuRoute
  '/turmas': typeof AppTurmasRoute
  '/turmas/$id': typeof AppTurmasIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/perfil': typeof AppPerfilRoute
  '/ru': typeof AppRuRoute
  '/turmas': typeof AppTurmasRoute
  '/': typeof AppIndexRoute
  '/turmas/$id': typeof AppTurmasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/ru': typeof AppRuRoute
  '/_app/turmas': typeof AppTurmasRoute
  '/_app/': typeof AppIndexRoute
  '/_app/turmas_/$id': typeof AppTurmasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/$' | '/' | '/login' | '/perfil' | '/ru' | '/turmas' | '/turmas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/login' | '/perfil' | '/ru' | '/turmas' | '/' | '/turmas/$id'
  id:
    | '__root__'
    | '/$'
    | '/_app'
    | '/login'
    | '/_app/perfil'
    | '/_app/ru'
    | '/_app/turmas'
    | '/_app/'
    | '/_app/turmas_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ru': {
      id: '/_app/ru'
      path: '/ru'
      fullPath: '/ru'
      preLoaderRoute: typeof AppRuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/turmas': {
      id: '/_app/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof AppTurmasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/turmas_/$id': {
      id: '/_app/turmas_/$id'
      path: '/turmas/$id'
      fullPath: '/turmas/$id'
      preLoaderRoute: typeof AppTurmasIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPerfilRoute: typeof AppPerfilRoute
  AppRuRoute: typeof AppRuRoute
  AppTurmasRoute: typeof AppTurmasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTurmasIdRoute: typeof AppTurmasIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPerfilRoute: AppPerfilRoute,
  AppRuRoute: AppRuRoute,
  AppTurmasRoute: AppTurmasRoute,
  AppIndexRoute: AppIndexRoute,
  AppTurmasIdRoute: AppTurmasIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
