[project]
name = "api"
description = "API pública do Followw UnB."
version = "0.0.1"
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "cryptography>=50.0.1",
    "fastapi[standard]>=0.141.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "qstash>=3.4.0",
    "sigaa-client",
    "sqlalchemy[asyncio]>=2.0.52",
]

[tool.uv.sources]
sigaa-client = { workspace = true }

[tool.vercel]
entrypoint = "api.main:app"

[project.scripts]
api = "api:main"
db-init = "api.db.main:db_init"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.ruff.format]
line-ending = "lf"

[tool.uv.build-backend]
module-root = ""

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "respx>=0.23.1",
    "ruff>=0.16.6",
]
